version: '3'

services:

  web:
    build:
      context: .
    container_name: react.web
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
